name: HACS Action

on:
  workflow_run:
    workflows: ["Copy to dist"]
    types:
      - completed

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
